// Mock roast engine. Swap `generateRoast` with a real fetch later.
// Usage: const result = await generateRoast({ content, level });

export type BurnLevel = 1 | 2 | 3;

export interface RoastInput {
  content: string;
  level: BurnLevel;
  source?: "pdf" | "url" | "text";
}

export interface RoastReport {
  cliche: number;
  readability: number;
  hireability: number;
  buzzwordDensity: number;
  honesty: number;
}

export interface RoastResult {
  roast: string;
  report: RoastReport;
  verdict: string;
  level: BurnLevel;
}

const ROASTS: Record<BurnLevel, { roasts: string[]; verdicts: string[] }> = {
  1: {
    roasts: [
      `Thanks for sending this over. We've reviewed your document carefully and would like to offer some "constructive feedback."

Your use of "team player" is a bold choice — bold in the sense that 4.2 million other resumes used it this quarter. Your bullet points have an interesting cadence, mostly because they all begin with "Responsible for," which historically translates to "did the bare minimum without setting anything on fire."

We particularly appreciated the line "results-driven professional with a passion for synergy." It really paints a picture. That picture is of someone who has not had a new thought since 2014.

We'll keep your application on file, which in HR is a phrase that means the same thing as "the recycling bin."`,
      `Hi there! Just a quick note on your submission.

We noticed you listed "Microsoft Word" as a skill. In 2026. Right next to "proficient in email." We're going to gently suggest that breathing oxygen is also not a competitive differentiator.

Your "Objective" section reads like it was generated by a LinkedIn AI that gave up halfway through. And while we admire the consistency of describing every job as "spearheading initiatives," we did want to mention that you cannot, in fact, spearhead a coffee run.

Best of luck in your continued search. Truly. We mean it. We have to say that.`,
    ],
    verdicts: ["Politely Declined", "Filed Under: No"],
  },
  2: {
    roasts: [
      `Okay so I just read this and I need a moment. A WHOLE moment.

First of all — the font. Calibri? In this economy? You're applying for jobs with the same font your dentist uses to print appointment reminders. Bold strategy.

You wrote "go-getter" UNIRONICALLY. You "wear many hats." Babe. Babe. Hats are not a personality. Also you "leveraged synergies to drive impact" which is corporate for "I attended meetings and occasionally spoke."

Your job titles have been quietly inflating since 2019 like crypto. You went from "intern" to "Senior Strategic Visionary of Operational Excellence" in 18 months. Sir. That is not a job. That is a haunted business card.

The skills section lists "communication" right above "team work" right above "Excel." We get it. You have been alive. Congratulations.

10/10 would not interview but absolutely would screenshot.`,
      `BESTIE. We need to talk.

You have "passionate about making a difference" in the summary. About what? You work in supply chain logistics for a midsize regional pretzel distributor. The difference you are making is roughly 14 cents per unit.

Every single bullet point starts with a verb that's trying SO hard. "Spearheaded." "Orchestrated." "Architected." You did NOT architect the new spreadsheet template, Brian. You opened a Google Sheet.

Also the LinkedIn headline says "I help brands tell their story." No you don't. You're unemployed. You're telling YOUR story, badly, to a recruiter named Madison who is currently on Bumble.

This is giving "main character of a Reddit post titled 'AITA for thinking I deserve $180k.'" 💀`,
    ],
    verdicts: ["Cooked", "Lightly Toasted"],
  },
  3: {
    roasts: [
      `Let's be precise, because you clearly weren't.

This document is not a résumé. It is a confession. A 1.5-page admission that you have spent the last decade mistaking motion for progress, calendars for accomplishment, and Slack messages for thinking. You have built a career out of being adjacent to work that other people did. The verbs you've chosen — "spearheaded," "championed," "drove" — are the linguistic equivalent of standing near a fire and warming your hands.

Your education section betrays you most. Not because the school is unimpressive, but because it is the most recent thing on this page that suggests genuine difficulty. Everything after graduation reads like the curriculum vitae of a man slowly negotiating with mediocrity until mediocrity agreed to call him a Director.

There is no through-line here. No discipline. No taste. Just a series of titles arranged in descending order of how much you'd like to talk about them at parties. The skills section — "leadership, communication, strategy" — is the part of the test you were supposed to fill in with answers.

You are not unhireable. You are something far worse. You are exactly hireable enough to keep doing this for thirty more years.`,
      `I have read your portfolio. I would like the time back, but I understand that is not how linear causality functions.

You describe yourself as a "creative thinker." This is the kind of self-assessment one offers when no one else has volunteered the descriptor on one's behalf in over a decade. Your case studies do not document creative thinking. They document the patient, methodical assembly of work that is technically defensible and spiritually inert.

Every project follows the same arc: a problem stated in the corporate passive voice, a process described in stock methodology nouns ("discovery," "ideation," "iteration"), and a result measured in metrics that, on inspection, would have happened anyway. You did not move the needle. The needle was on a treadmill, and you happened to be standing nearby holding a clipboard.

The most damning thing in this document is the "About" page. Not because it is poorly written — it is competently written, which is part of the problem — but because after reading it, I could not tell you a single thing you actually believe. You have curated yourself into invisibility. You are a LinkedIn profile in human form: optimized, inoffensive, and impossible to remember.

I am not angry. I am simply now aware of you, which I suspect is the worst review you have ever received.`,
    ],
    verdicts: ["Existentially Incinerated", "Reduced to Component Atoms"],
  },
};

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function reportFor(level: BurnLevel): RoastReport {
  const base = {
    1: { cliche: 78, readability: 45, hireability: 38, buzzwordDensity: 71, honesty: 22 },
    2: { cliche: 92, readability: 28, hireability: 14, buzzwordDensity: 88, honesty: 9 },
    3: { cliche: 97, readability: 12, hireability: 2, buzzwordDensity: 95, honesty: 4 },
  }[level];
  // Tiny jitter so it feels alive
  const j = (n: number) => Math.max(1, Math.min(99, n + Math.floor(Math.random() * 7) - 3));
  return {
    cliche: j(base.cliche),
    readability: j(base.readability),
    hireability: j(base.hireability),
    buzzwordDensity: j(base.buzzwordDensity),
    honesty: j(base.honesty),
  };
}

export async function generateRoast(input: RoastInput): Promise<RoastResult> {
  // Simulate latency for the dramatic terminal sequence
  await new Promise((r) => setTimeout(r, 3000));

  const bucket = ROASTS[input.level];
  return {
    roast: pick(bucket.roasts),
    verdict: pick(bucket.verdicts),
    report: reportFor(input.level),
    level: input.level,
  };
}

export const LEVEL_META: Record<BurnLevel, { name: string; tagline: string; color: string }> = {
  1: { name: "Passive-Aggressive", tagline: "Recruiter rejection email energy", color: "ember" },
  2: { name: "Roast", tagline: "Group chat screenshot material", color: "primary" },
  3: { name: "Psychological Warfare", tagline: "You'll need therapy", color: "destructive" },
};

export const TERMINAL_LOGS = [
  "> Initializing crematorium furnace...",
  "> Scanning for 'Team Player' clichés......... [142 found]",
  "> Detecting inflated job titles............. [CRITICAL]",
  "> Cross-referencing buzzword database....... [overflow]",
  "> Calculating levels of disappointment...... [█████████░]",
  "> Locating original thought.................. [404 NOT FOUND]",
  "> Assembling brutal honesty payload.........",
  "> Loading sarcasm.dll........................ [OK]",
  "> Igniting...",
];
